################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/hts221/hts221.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/hts221/hts221_reg.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis2dw12/lis2dw12.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis2dw12/lis2dw12_reg.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis2mdl/lis2mdl.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis2mdl/lis2mdl_reg.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis3dhh/lis3dhh.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis3dhh/lis3dhh_reg.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lps22hh/lps22hh.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lps22hh/lps22hh_reg.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lsm6dsox/lsm6dsox.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lsm6dsox/lsm6dsox_reg.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/stts751/stts751.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/Components/stts751/stts751_reg.c 

OBJS += \
./Drivers/BSP/Components/hts221.o \
./Drivers/BSP/Components/hts221_reg.o \
./Drivers/BSP/Components/lis2dw12.o \
./Drivers/BSP/Components/lis2dw12_reg.o \
./Drivers/BSP/Components/lis2mdl.o \
./Drivers/BSP/Components/lis2mdl_reg.o \
./Drivers/BSP/Components/lis3dhh.o \
./Drivers/BSP/Components/lis3dhh_reg.o \
./Drivers/BSP/Components/lps22hh.o \
./Drivers/BSP/Components/lps22hh_reg.o \
./Drivers/BSP/Components/lsm6dsox.o \
./Drivers/BSP/Components/lsm6dsox_reg.o \
./Drivers/BSP/Components/stts751.o \
./Drivers/BSP/Components/stts751_reg.o 

C_DEPS += \
./Drivers/BSP/Components/hts221.d \
./Drivers/BSP/Components/hts221_reg.d \
./Drivers/BSP/Components/lis2dw12.d \
./Drivers/BSP/Components/lis2dw12_reg.d \
./Drivers/BSP/Components/lis2mdl.d \
./Drivers/BSP/Components/lis2mdl_reg.d \
./Drivers/BSP/Components/lis3dhh.d \
./Drivers/BSP/Components/lis3dhh_reg.d \
./Drivers/BSP/Components/lps22hh.d \
./Drivers/BSP/Components/lps22hh_reg.d \
./Drivers/BSP/Components/lsm6dsox.d \
./Drivers/BSP/Components/lsm6dsox_reg.d \
./Drivers/BSP/Components/stts751.d \
./Drivers/BSP/Components/stts751_reg.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/Components/hts221.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/hts221/hts221.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/hts221_reg.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/hts221/hts221_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lis2dw12.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis2dw12/lis2dw12.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lis2dw12_reg.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis2dw12/lis2dw12_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lis2mdl.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis2mdl/lis2mdl.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lis2mdl_reg.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis2mdl/lis2mdl_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lis3dhh.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis3dhh/lis3dhh.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lis3dhh_reg.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lis3dhh/lis3dhh_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lps22hh.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lps22hh/lps22hh.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lps22hh_reg.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lps22hh/lps22hh_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lsm6dsox.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lsm6dsox/lsm6dsox.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/lsm6dsox_reg.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/lsm6dsox/lsm6dsox_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/stts751.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/stts751/stts751.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/stts751_reg.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/Components/stts751/stts751_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-Components

clean-Drivers-2f-BSP-2f-Components:
	-$(RM) ./Drivers/BSP/Components/hts221.cyclo ./Drivers/BSP/Components/hts221.d ./Drivers/BSP/Components/hts221.o ./Drivers/BSP/Components/hts221.su ./Drivers/BSP/Components/hts221_reg.cyclo ./Drivers/BSP/Components/hts221_reg.d ./Drivers/BSP/Components/hts221_reg.o ./Drivers/BSP/Components/hts221_reg.su ./Drivers/BSP/Components/lis2dw12.cyclo ./Drivers/BSP/Components/lis2dw12.d ./Drivers/BSP/Components/lis2dw12.o ./Drivers/BSP/Components/lis2dw12.su ./Drivers/BSP/Components/lis2dw12_reg.cyclo ./Drivers/BSP/Components/lis2dw12_reg.d ./Drivers/BSP/Components/lis2dw12_reg.o ./Drivers/BSP/Components/lis2dw12_reg.su ./Drivers/BSP/Components/lis2mdl.cyclo ./Drivers/BSP/Components/lis2mdl.d ./Drivers/BSP/Components/lis2mdl.o ./Drivers/BSP/Components/lis2mdl.su ./Drivers/BSP/Components/lis2mdl_reg.cyclo ./Drivers/BSP/Components/lis2mdl_reg.d ./Drivers/BSP/Components/lis2mdl_reg.o ./Drivers/BSP/Components/lis2mdl_reg.su ./Drivers/BSP/Components/lis3dhh.cyclo ./Drivers/BSP/Components/lis3dhh.d ./Drivers/BSP/Components/lis3dhh.o ./Drivers/BSP/Components/lis3dhh.su ./Drivers/BSP/Components/lis3dhh_reg.cyclo ./Drivers/BSP/Components/lis3dhh_reg.d ./Drivers/BSP/Components/lis3dhh_reg.o ./Drivers/BSP/Components/lis3dhh_reg.su ./Drivers/BSP/Components/lps22hh.cyclo ./Drivers/BSP/Components/lps22hh.d ./Drivers/BSP/Components/lps22hh.o ./Drivers/BSP/Components/lps22hh.su ./Drivers/BSP/Components/lps22hh_reg.cyclo ./Drivers/BSP/Components/lps22hh_reg.d ./Drivers/BSP/Components/lps22hh_reg.o ./Drivers/BSP/Components/lps22hh_reg.su ./Drivers/BSP/Components/lsm6dsox.cyclo ./Drivers/BSP/Components/lsm6dsox.d ./Drivers/BSP/Components/lsm6dsox.o ./Drivers/BSP/Components/lsm6dsox.su ./Drivers/BSP/Components/lsm6dsox_reg.cyclo ./Drivers/BSP/Components/lsm6dsox_reg.d ./Drivers/BSP/Components/lsm6dsox_reg.o ./Drivers/BSP/Components/lsm6dsox_reg.su ./Drivers/BSP/Components/stts751.cyclo ./Drivers/BSP/Components/stts751.d ./Drivers/BSP/Components/stts751.o ./Drivers/BSP/Components/stts751.su ./Drivers/BSP/Components/stts751_reg.cyclo ./Drivers/BSP/Components/stts751_reg.d ./Drivers/BSP/Components/stts751_reg.o ./Drivers/BSP/Components/stts751_reg.su

.PHONY: clean-Drivers-2f-BSP-2f-Components

