################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_bus.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_env_sensors.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_env_sensors_ex.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_motion_sensors.c \
/home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_motion_sensors_ex.c 

OBJS += \
./Drivers/BSP/SensorTileBox/SensorTile.box.o \
./Drivers/BSP/SensorTileBox/SensorTile.box_bus.o \
./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors.o \
./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors_ex.o \
./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors.o \
./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors_ex.o 

C_DEPS += \
./Drivers/BSP/SensorTileBox/SensorTile.box.d \
./Drivers/BSP/SensorTileBox/SensorTile.box_bus.d \
./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors.d \
./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors_ex.d \
./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors.d \
./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/SensorTileBox/SensorTile.box.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box.c Drivers/BSP/SensorTileBox/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/SensorTileBox/SensorTile.box_bus.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_bus.c Drivers/BSP/SensorTileBox/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_env_sensors.c Drivers/BSP/SensorTileBox/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors_ex.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_env_sensors_ex.c Drivers/BSP/SensorTileBox/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_motion_sensors.c Drivers/BSP/SensorTileBox/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors_ex.o: /home/dell/Assignment/assignment/demo/Drivers/BSP/SensorTile.box/SensorTile.box_motion_sensors_ex.c Drivers/BSP/SensorTileBox/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DSTM32L4R9xx -DUSE_HAL_DRIVER -DSTM32_SENSORTILEBOX -c -I../../../Inc -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../../Drivers/BSP/Components/lsm6dsox -I../../../../../../../Drivers/BSP/Components/lis3dhh -I../../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../../Drivers/BSP/Components/stts751 -I../../../../../../../Drivers/BSP/SensorTile.box -I../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -O0 -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-SensorTileBox

clean-Drivers-2f-BSP-2f-SensorTileBox:
	-$(RM) ./Drivers/BSP/SensorTileBox/SensorTile.box.cyclo ./Drivers/BSP/SensorTileBox/SensorTile.box.d ./Drivers/BSP/SensorTileBox/SensorTile.box.o ./Drivers/BSP/SensorTileBox/SensorTile.box.su ./Drivers/BSP/SensorTileBox/SensorTile.box_bus.cyclo ./Drivers/BSP/SensorTileBox/SensorTile.box_bus.d ./Drivers/BSP/SensorTileBox/SensorTile.box_bus.o ./Drivers/BSP/SensorTileBox/SensorTile.box_bus.su ./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors.cyclo ./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors.d ./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors.o ./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors.su ./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors_ex.cyclo ./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors_ex.d ./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors_ex.o ./Drivers/BSP/SensorTileBox/SensorTile.box_env_sensors_ex.su ./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors.cyclo ./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors.d ./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors.o ./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors.su ./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors_ex.cyclo ./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors_ex.d ./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors_ex.o ./Drivers/BSP/SensorTileBox/SensorTile.box_motion_sensors_ex.su

.PHONY: clean-Drivers-2f-BSP-2f-SensorTileBox

